### ISSUE TITLE
Can't get project to run

### ISSUE THREAD

**Issue by stowball** [chris-pearce/scally#51]
I've tried cloning and following the instructions, or installing from npm and then following the instructions, but as soon as I start the Sass watch, I get this in style.css:

```
Syntax error: "h1, .h1", "h2, .h2", "h3, .h3" can't extend: invalid selector
        on line 34 of bower_components\scally\core\base\_headings.scss, in `@content'
        from line 39 of bower_components\scally\core\mixins\_target-headings.scss, in `headings'
        from line 33 of bower_components\scally\core\base\_headings.scss
        from line 154 of style.scss
```

**Comment by chris-pearce** [comment]
@stowball I just got it running with the npm & Bower install options fine. I think you might have missed the manual part of setting up a master `style.scss`: https://github.com/chris-pearce/scally#setting-up-your-master-stylesheet? Then making sure the Scally partial paths are correct in that stylesheet i.e. linking to either `node_modules/scally` or `bower_components/scally`. Here's my npm install:

![screen shot 2015-03-22 at 11 18 22 pm](https://cloud.githubusercontent.com/assets/1342772/6769309/4fbccbe0-d0ea-11e4-9f90-06732e05a3a2.png)

If not let's go over it in person tomorrow :+1:.

_The Scally setup is not as smooth as I'd like which is why I have this issue: https://github.com/chris-pearce/scally/issues/8._

**Comment by chris-pearce** [comment]
@stowball still an issue?

**Comment by stowball** [comment]
Nope. I just re-read the instructions and figured it out! Thanks
